TurboBlog/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TurboBlog.Models
{
    public class Article
    {
        public int Id { get; set; }

        public string Title { get; set; }
        public string Content { get; set; }

        public DateTime CreationTime { get; set; }

        public Article()
        {
        }

        public Article(string title, string content)
        {
            Title = title;
            Content = content;
            CreationTime = DateTime.Now;
        }
    }
}

TurboBlog/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TurboBlog.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }

        public Author()
        {
        }

        public Author(string login, string password)
        {
            Login = login;
            Password = password;
        }
    }
}

TurboBlog/Models/ErrorViewModel.cs
using System;

namespace TurboBlog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TurboBlog/Controllers/ArticleController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TurboBlog.Database;
using TurboBlog.Models;

namespace TurboBlog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IGeneralContext _context;

        public ArticleController(IGeneralContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Submit()
        {
            var form = HttpContext.Request.Form;
            _context.Articles.Add(new Article(form["title"], form["article"]));
            _context.UpdateChanges();
            return View();
        }

        public IActionResult CurrentArticle(int articleId)
        {
            return View(_context.Articles.ToArray()[articleId]);
            //return View(context.Articles.First(art => art.Id == articleId));
        }
    }
}

TurboBlog/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TurboBlog.Controllers
{
    public class HelloWorldController : Controller
    {
        // GET: HelloWorld
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello" + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
}

TurboBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using TurboBlog.Database;
using TurboBlog.Models;

namespace TurboBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGeneralContext _context;

        public HomeController(IGeneralContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult UserLogged()
        {
            var form = HttpContext.Request.Form;
            var login = form["login"];
            var password = form["password"];
            Response.Cookies.Append("login", login);
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private bool Contains(string login)
        {
            return true;
        }
        private bool Check(string login, string password)
        {
            return true;
        }
    }
}

TurboBlog/Views/Article/Create.cshtml
@{
    ViewData["Title"] = "CreateArticle";
}

<div class="text-center">
    <h1 class="display-4">Tell us your story!</h1>
    <form enctype="multipart/form-data" method="post" asp-action="Submit" asp-controller="Article">
        Title:
        <p> <input type="text" autocomplete="off" name="title" size="48" /></p>

        Article:
        <p><textarea rows="20" cols="50" name="article"></textarea></p>

        Author:
        <p><input type="text" autocomplete="off" name="author" size="48"/></p>

        <p><input type="submit" value="Publish"></p>
    </form>
</div>

TurboBlog/Views/Article/CurrentArticle.cshtml
@model Article
@{
    ViewData["Title"] = "Article";
}
<div class="text-center">
    <h1>@Model.Title</h1>
    <p>@Model.Content</p>
    <p>Back to <a href="https://localhost:44366/Home">Home page.</a></p>
</div>

TurboBlog/Views/Article/Submit.cshtml
@{
    ViewData["Title"] = "ArticleSubmitted";
}

<div class="text-center">
    <h1 class="display-4">Your story was published!</h1>
    <p>Back to <a href="https://localhost:44366/Home">Home page.</a></p>
</div>

TurboBlog/Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Blog";
}

<div class="text-center">
    <h1 class="display-4">Welcome to TubroBlog</h1>
    <p>Look through the articles made by Authors:</p>
</div>
<ul>
    @for (int i = 0; i < 10; i++)
    {
        <li>article</li>
    }
</ul>

TurboBlog/Views/HelloWorld/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2> Welcome </h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

TurboBlog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model TurboBlog.Database.IGeneralContext

<div class="text-center">
    <h1 class="display-4">Welcome to TurboBlog</h1>
    <p>You can <a href="https://localhost:44366/Article/Create">create an article.</a></p>
    <p>Look through the articles made by Authors:</p>
</div>
<ul>
    @foreach (Article art in Model.Articles)
    {
        //<li><a href="https://localhost:44366/Article/CurrentArticle">@art.Title</a></li>

        <button type="button" onclick="location.href = '@Url.Action("CurrentArticle", "Article", art.Id)'">@art.Title</button>
    }
</ul>

TurboBlog/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="text-center">
    <form enctype="multipart/form-data" method="post" asp-action="UserLogged" asp-controller="Home">
        Login:
        <p> <input type="text" name="login" /></p>
        Password:
        <p><input type="text" autocomplete="off" name="password" /> </p>
        <p><input type="submit" value="Login"></p>
    </form>
</div>

TurboBlog/Views/Home/UserLogged.cshtml
@{
    ViewData["Title"] = "UserLogged";
}

<div class="text-center">
    <h1 class="display-4">You are in!</h1>
    <p>Back to <a href="https://localhost:44366/Home">Home page.</a></p>
</div>

TurboBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TurboBlog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TurboBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TurboBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>